// Log to console
console.log('Hello World');
console.log(123);
console.log(true);
var greeting = 'good morning';
console.log(greeting);
console.log([1, 2, 3, 4, 5]);
console.log({ a: 1, b: 2 });
console.table({ a: 1, b: 2 });
console.error('This is a error');
console.clear();
console.warn('This is a warning');
console.time('time');
console.log('hello');
console.log('hello');
console.log('hello');
console.log('hello');
console.log('hello');
console.log('hello');
console.timeEnd('time');
